name: 🐛 Bug Report
description: Help us get better
labels:
- "bug"
projects:
- "MikronT/1"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        We appreciate your effort to help us get better!

        Please search for [existing issues](https://github.com/MikronT/TACC-Green1/issues) before filing a new one!

  - type: markdown
    attributes:
      value: |
        # Environment
        Tell us about the test environment the bug happens in

  - type: checkboxes
    attributes:
      label: 💽 Operating System
      description: What OS types are you experiencing the bug on?
      multiple: true
      options:
        - label: Android
        - label: iOS
        - label: Windows
        - label: Mac
        - label: Some Linux distro
        - label: Other OS
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: 🌎 Browser
      description: What browsers do you see the problem on?
      multiple: true
      options:
        - label: Google Chrome
        - label: Mozilla Firefox
        - label: Safari
        - label: Vivaldi
        - label: Microsoft Edge
        - label: Opera
        - label: Other browser
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: 🆕 Version
      description: Confirm are running the [latest](https://github.com/MikronT/TACC-Green1/releases/latest) version of our software
      options:
        - label: I am sure I am experiencing the bug on the latest version
          required: true

  - type: markdown
    attributes:
      value: |
        # Reproduction
        Tell us how can we reproduce the bug

  - type: textarea
    attributes:
      label: ℹ Preconditions
      description: Actions to be done before the start of the bug reproducing
      placeholder: Create an item in the DB: `INSERT INTO table1 (column1, column2) VALUES (value1, value2);`
    validations:
      required: false

  - type: textarea
    attributes:
      label: 📝 Steps to Reproduce
      description: Detailed steps to help us reproduce the bug
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    attributes:
      label: ℹ Postconditions
      description: Actions to be done after the bug reproduction
      placeholder: Delete created item from the DB: `DELETE FROM table1 WHERE id=<item1_id>;`
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        # Behavior
        Tell us about the behavior of the software and your expectations

  - type: textarea
    attributes:
      label: ✔️ Expected Behavior
      description: What were you expecting?
    validations:
      required: false

  - type: textarea
    attributes:
      label: ❌ Actual Behavior
      description: What happened instead?
    validations:
      required: false

  - type: textarea
    attributes:
      label: 📝 Log Output
      description: If available, paste the browser console log output here
      render: shell
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        # Links to Requirements
        Link appropriate issues with the '#' symbol

  - type: textarea
    attributes:
      label: 🔗 User Story
      description: What user story describes the expected behavior
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🔗 Test Case
      description: What test case is related to the bug
    validations:
      required: true
