name: 🐛 Bug Report
description: Help us get better
labels:
- "bug"
projects:
- "MikronT/1"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        We appreciate your effort to help us get better!

        Please search for [existing issues](https://github.com/MikronT/TACC-Green1/issues) before filing a new one!

  - type: markdown
    attributes:
      value: "# Environment"
      description: Tell us about the test environment the bug happens in

  - type: dropdown
    attributes:
      label: 💽 Operating System
      description: What OS types are you experiencing the bug on?
      multiple: true
      options:
        - Android
        - iOS
        - Windows
        - Mac
        - Some Linux distro
        - Other OS
    validations:
      required: true

  - type: dropdown
    attributes:
      label: 🌎 Browser
      description: What browsers do you see the problem on?
      multiple: true
      options:
        - Google Chrome
        - Mozilla Firefox
        - Safari
        - Vivaldi
        - Microsoft Edge
        - Opera
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: 🆕 Version
      description: Confirm are running the [latest](https://github.com/MikronT/TACC-Green1/releases/latest) version of our software
      options:
        - label: I am sure I am experiencing the bug on the latest version
          required: true

  - type: markdown
    attributes:
      value: "# Reproduction"

  - type: textarea
    attributes:
      label: ℹ Preconditions
      description: |
        Actions to be done before the start of the bug reproducing
        Example: "Create an item in the DB: INSERT INTO table1 (column1, column2) VALUES (value1, value2);"
    validations:
      required: false

  - type: textarea
    attributes:
      label: 📝 Steps to Reproduce
      description: Detailed steps to help us reproduce the bug
    validations:
      required: true

  - type: textarea
    attributes:
      label: ℹ Postconditions
      description: |
        Actions to be done after the bug reproduction
        Example: "Delete created item from the DB: DELETE FROM table1 WHERE id=<item1_id>;"
    validations:
      required: false

  - type: markdown
    attributes:
      value: "# Behavior"
      description: Tell us about the behavior of the software and your expectations

  - type: textarea
    attributes:
      label: ✔️ Expected Behavior
      description: What were you expecting?
    validations:
      required: false

  - type: textarea
    attributes:
      label: ❌ Actual Behavior
      description: What happened instead?
    validations:
      required: false

  - type: textarea
    attributes:
      label: 📝 Log Output
      description: If available, paste the browser console log output here
      render: shell
    validations:
      required: false

  - type: markdown
    attributes:
      value: "# Links to Requirements"
      description: Link appropriate issues with the '#' symbol

  - type: textarea
    attributes:
      label: 🔗 User Story
      description: What user story describes the expected behavior
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🔗 Test Case
      description: What test case is related to the bug
    validations:
      required: true
